allowBuilds:
  electron: true
  esbuild: true
  sharp: true
  "@electron/node-gyp": true

minimumReleaseAgeExclude:
  - electron@42.5.1

nodeLinker: hoisted

overrides:
  "@electron/node-gyp": "npm:@electron/node-gyp@10.2.0-electron.1"
